Feature/145 add onboarding to readme
SKF/ferris pull request #147
Opened 2021-07-05 13:24 UTC by raggeju

2021-07-05 13:52 UTC, tobiasljungstrom requested changes
Good stuff, just one step in the installation missing. 👍🏻

2021-07-05 13:52 UTC, tobiasljungstrom commented on README.md
> +## 👶 Installation
We need to add the .npmrc configuration here, since @SKF packages aren't hosted on the public npm or yarn repos.

2021-07-05 13:52 UTC, tobiasljungstrom commented on README.md
> +import { Sample } from '@skf/ferris';
Better to use a real component as example I think?

2021-07-06 13:45 UTC, raggeju commented on README.md
> +## 👶 Installation
What does this mean? That we show the user from the Readme how to set that file up?

2021-07-06 13:54 UTC, tobiasljungstrom commented on README.md
> +## 👶 Installation
Yes, that what I was thinking. If they try to just "yarn add @skf/ferris" they will get an error saying it can't be found on the yarn registry.

2021-07-06 14:16 UTC, tobiasljungstrom approved these changes
Let's gooo

2021-07-06 14:16 UTC, merged