Fix RadioField comments
SKF/ferris pull request #190
Opened 2021-08-20 12:29 UTC by raggeju

Add controlled variant and more...

2021-08-20 12:31 UTC, stt-tomahl submitted a review, later dismissed

2021-08-20 13:09 UTC, tobiasljungstrom requested changes

2021-08-20 13:09 UTC, tobiasljungstrom commented on src/atoms/radio/Radio.tsx
> +		const inputRef = useRef<HTMLInputElement>(null),
It doesn't look like we use the inputRef for anything, so if we remove it  we can also remove mergeRefs, and then just put the forwarded ref directly on the input element.

2021-08-23 09:41 UTC, raggeju commented on src/atoms/radio/Radio.tsx
> +		const inputRef = useRef<HTMLInputElement>(null),
I don't understand. inputRef is used in line 42 when creating mergedRefs. And mergedRefs is used on line 53..

2021-08-23 11:35 UTC, tobiasljungstrom commented on src/atoms/radio/Radio.tsx
> +		const inputRef = useRef<HTMLInputElement>(null),
Ah, yes, but it has no effect on any behaviour. We never use inputRef.current anywhere, for any kind of side effects or anything. So line 53 could just be ref={ref} so that the forwarding works, and that's it.

2021-08-23 12:16 UTC, tobiasljungstrom approved these changes
Snyggt

2021-08-23 12:41 UTC, merged