Feature(Progress bar): Make progress bar more accessible
SKF/ferris pull request #277
Opened 2021-09-27 12:36 UTC by tobiasljungstrom

I was contemplating switching to the <progress> element, but it would need a rework of the styling, and I'm pretty sure this covers the same bases.

Closes #276

2021-09-28 07:37 UTC, raggeju commented on src/atoms/progress-bar/ProgressBar.tsx
> +			title={title}
Default value?

2021-09-29 09:04 UTC, tobiasljungstrom commented on src/atoms/progress-bar/ProgressBar.tsx
> +			title={title}
Yeah, let's do the same as for the loading spinner to keep it consistent.

2021-09-29 09:50 UTC, tomahl approved these changes

2021-09-29 10:02 UTC, raggeju requested changes

2021-09-29 10:02 UTC, raggeju commented on src/atoms/progress-bar/ProgressBar.stories.tsx
> +			defaultValue: 'Loading cool data',
This will only give it a defaultValue in the storybook, which is good but don't we want a default value in the real world as well?

2021-09-29 11:14 UTC, tobiasljungstrom commented on src/atoms/progress-bar/ProgressBar.stories.tsx
> +			defaultValue: 'Loading cool data',
Oh yes, there is one on line 37 in ProgressBar.tsx!

2021-09-29 12:43 UTC, raggeju approved these changes

2021-09-29 14:46 UTC, merged